level_limit: 3
cache_enabled: false
api_key: <%= ENV['API_KEY'] || 'PUT_YOUR_API_KEY_HERE' %>
elasticsearch_server: <%= ENV['SEARCH_SERVER'] || 'http://localhost:9200' %>
cache_timeout:
  threads_search: 10
  threads_query: 10
max_deep_search_comment_count: 5000
