# This is only currently used by Travis for testing
version: "2"

services:
  elasticsearch:
    image: elasticsearch:1.5.2
    container_name: "es.edx"
  mongo:
    image: mongo:3.0.14
    container_name: "mongo.edx"
  forum:
    image: edxops/forums:latest

    container_name: forum_testing
    volumes:
      - ..:/edx/app/forum/cs_comments_service
    command: tail -f /dev/null
    depends_on:
          - "elasticsearch"
          - "mongo"
